name: vbeach
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - tqdm
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1
  - scipy
  - numpy
  - matplotlib
  - pandas
  - scikit-learn
  - opencv
  - pip
  - pip:
    - torch-scatter==2.1.1+cu121 --find-links https://data.pyg.org/whl/torch-2.0.1+cu121.html
    - segmentation-models-pytorch==0.2.0
