name: vbeach
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - tqdm
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8
  - scipy
  - numpy
  - matplotlib
  - pandas
  - scikit-learn
  - opencv
  - pip
  - pip:
    - pip install torch-scatter -f https://data.pyg.org/whl/torch-2.1.0+cu118.html
    - segmentation-models-pytorch==0.2.0
